### ISSUE TITLE
Crash in 2.14.1

### ISSUE THREAD

**Issue by BLTuckerDev** [Wootric/WootricSDK-Android#81]
We recently updated to version 2.14.1 and are now seeing crashes coming from the WootricCustomThankYou class. It looks similar to the issue reported [here](https://github.com/Wootric/WootricSDK-Android/issues/79)

Are there any known work arounds? Or would the advice be to roll back to an older version of the library?
 I've attached a stack trace below:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.getBoolean(java.lang.String)' on a null object reference
       at com.wootric.androidsdk.objects.WootricCustomThankYou.fromJson(WootricCustomThankYou.java:422)
       at com.wootric.androidsdk.objects.Settings.fromJson(Settings.java:758)
       at com.wootric.androidsdk.network.tasks.CheckEligibilityTask.onSuccess(CheckEligibilityTask.java:123)
       at com.wootric.androidsdk.network.tasks.WootricRemoteRequestTask.onPostExecute(WootricRemoteRequestTask.java:121)
       at com.wootric.androidsdk.network.tasks.WootricRemoteRequestTask.onPostExecute(WootricRemoteRequestTask.java:44)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by diegoserranoa** [comment]
@BLTuckerDev hi Brett, thanks for reporting this. We're looking into this issue. I'll let you knos as soon as we have a fix.

Thanks

**Comment by diegoserranoa** [comment]
Hi @BLTuckerDev we released a new version today. We hope this fixes your issue!

**Comment by BLTuckerDev** [comment]
Thank you so much!
