### ISSUE TITLE
NullPointerException in Survey Fragment

### ISSUE THREAD

**Issue by bpasha90** [Wootric/WootricSDK-Android#88]
### Summary
We have been facing a fatal exception in our android production build. Please refer to the stacktrace below

### Wootric version
2.16.0

### Exception
`Caused by java.lang.NullPointerException
Attempt to invoke interface method 'void com.wootric.androidsdk.views.OnSurveyFinishedListener.onSurveyFinished()' on a null object reference
com.wootric.androidsdk.views.SurveyFragment.onDestroy `

### StackTrace
**Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.wootric.androidsdk.views.OnSurveyFinishedListener.onSurveyFinished()' on a null object reference
       at com.wootric.androidsdk.views.SurveyFragment.onDestroy(SurveyFragment.java:364)**

       at android.app.Fragment.performDestroy(Fragment.java:2782)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1451)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1576)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1637)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManagerImpl.java:3046)
       at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:3026)
       at android.app.FragmentController.dispatchDestroy(FragmentController.java:248)
       at android.app.Activity.performDestroy(Activity.java:7406)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1328)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4680)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4713)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4997)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4930)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by diegoserranoa** [comment]
Hello @bpasha90 
Are you sure you're using the latest version? This was fixed in the latest release.

In fact, from looking at the logs you provided `com.wootric.androidsdk.views.SurveyFragment.onDestroy(SurveyFragment.java:364)` it says the error is happening in line 364, and that is the exact line where we check if the object is null https://github.com/Wootric/WootricSDK-Android/blob/master/androidsdk/src/main/java/com/wootric/androidsdk/views/SurveyFragment.java#L364

**Comment by bpasha90** [comment]
**@diegoserranoa** Yeah sorry for that, the exceptions were actually on the releases that were build with wootric sdk release **2.15.0** .
Thanks for the help.

**Comment by diegoserranoa** [comment]
Great! Glad that's fixed.
